### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by AshutoshDemocrat** [RoundBearChoi/2.5D_Platformer_Unity_URP#2]
Hello,
I am getting error while building the game for PC. : 

Assets\2.5D Platformer\Essential\Character Control\AbilitySystem\Abilities\TransitionConditionChecker.cs(3,7): error CS0246: The type or namespace name 'UnityEditorInternal' could not be found (are you missing a using directive or an assembly reference?

Can you please look into it.

**Comment by Stand1k** [comment]
Hello, replace the script HierarchyWindowGroupHeader.cs
I have attached the replacement file
[HierarchyWindowGroupHeader.zip](https://github.com/RoundBearChoi/2.5D_Platformer_Unity_URP/files/6715328/HierarchyWindowGroupHeader.zip)
